"""Quality-biased universe of publicly traded companies.

This is not the entire market. Names are chosen because they are typically
large, liquid, and operationally established — the screener still has to
prove each name is well-run and macro-suppressed.
"""

from __future__ import annotations

QUALITY_UNIVERSE: tuple[str, ...] = (
    # Technology
    "AAPL",
    "MSFT",
    "GOOGL",
    "AMZN",
    "META",
    "NVDA",
    "AVGO",
    "ORCL",
    "ADBE",
    "CRM",
    "NOW",
    "INTU",
    "CSCO",
    "AMD",
    "QCOM",
    "TXN",
    "IBM",
    # Healthcare
    "UNH",
    "JNJ",
    "LLY",
    "ABBV",
    "MRK",
    "TMO",
    "ABT",
    "DHR",
    "ISRG",
    "SYK",
    "PFE",
    # Financials
    "JPM",
    "V",
    "MA",
    "BRK-B",
    "GS",
    "MS",
    "BLK",
    "SPGI",
    "AXP",
    "BAC",
    # Consumer
    "COST",
    "WMT",
    "HD",
    "PG",
    "KO",
    "PEP",
    "NKE",
    "MCD",
    "SBUX",
    "TJX",
    "LOW",
    # Industrials
    "CAT",
    "HON",
    "UNP",
    "GE",
    "DE",
    "LMT",
    "UPS",
    "ETN",
    "RTX",
    # Energy / materials / other
    "XOM",
    "CVX",
    "LIN",
    "NEE",
    "PLD",
    "NFLX",
    "DIS",
    "TSLA",
)

MARKET_TICKER = "SPY"

SECTORS: dict[str, str] = {
    "AAPL": "Technology",
    "MSFT": "Technology",
    "GOOGL": "Technology",
    "AMZN": "Consumer Cyclical",
    "META": "Technology",
    "NVDA": "Technology",
    "AVGO": "Technology",
    "ORCL": "Technology",
    "ADBE": "Technology",
    "CRM": "Technology",
    "NOW": "Technology",
    "INTU": "Technology",
    "CSCO": "Technology",
    "AMD": "Technology",
    "QCOM": "Technology",
    "TXN": "Technology",
    "IBM": "Technology",
    "UNH": "Healthcare",
    "JNJ": "Healthcare",
    "LLY": "Healthcare",
    "ABBV": "Healthcare",
    "MRK": "Healthcare",
    "TMO": "Healthcare",
    "ABT": "Healthcare",
    "DHR": "Healthcare",
    "ISRG": "Healthcare",
    "SYK": "Healthcare",
    "PFE": "Healthcare",
    "JPM": "Financial Services",
    "V": "Financial Services",
    "MA": "Financial Services",
    "BRK-B": "Financial Services",
    "GS": "Financial Services",
    "MS": "Financial Services",
    "BLK": "Financial Services",
    "SPGI": "Financial Services",
    "AXP": "Financial Services",
    "BAC": "Financial Services",
    "COST": "Consumer Defensive",
    "WMT": "Consumer Defensive",
    "HD": "Consumer Cyclical",
    "PG": "Consumer Defensive",
    "KO": "Consumer Defensive",
    "PEP": "Consumer Defensive",
    "NKE": "Consumer Cyclical",
    "MCD": "Consumer Cyclical",
    "SBUX": "Consumer Cyclical",
    "TJX": "Consumer Cyclical",
    "LOW": "Consumer Cyclical",
    "CAT": "Industrials",
    "HON": "Industrials",
    "UNP": "Industrials",
    "GE": "Industrials",
    "DE": "Industrials",
    "LMT": "Industrials",
    "UPS": "Industrials",
    "ETN": "Industrials",
    "RTX": "Industrials",
    "XOM": "Energy",
    "CVX": "Energy",
    "LIN": "Basic Materials",
    "NEE": "Utilities",
    "PLD": "Real Estate",
    "NFLX": "Communication Services",
    "DIS": "Communication Services",
    "TSLA": "Consumer Cyclical",
}

MIN_HOLD_DAYS = 14
MAX_HOLD_DAYS = 365
MIN_COMPANIES = 1
MAX_COMPANIES = 12
DEFAULT_MAX_PRICE = 500.0
DEFAULT_HOLD_DAYS = 90
DEFAULT_COMPANIES = 5
